### PR TITLE
Add AWS GovCloud partition support

### PR DESCRIPTION
**Pull request by thatsamguy**
Ref: "AWS Management Console with SAML" - https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html

Tested successfully with both commercial (`aws`) and govcloud (`aws-us-gov`) AWS partitions.

### CODE REVIEW

**Comment by thatsamguy** [comment]
Not quite ready yet.

**Comment by speshak** [comment]
Thanks for the contribution!
I don't have access to any accounts in the govcloud partition to test, but the change seems to make sense.  I have confirmed that this doesn't cause any regressions in the commercial partition.  I'm going to merge this and work on getting a v1.6 release cut.

**Comment by speshak** [comment]
Release 1.6.1 has been submitted to Mozilla for approval.

**Comment by speshak** [comment]
Mozilla has approved 1.6.1.  The Chrome version has been submitted to Google.

**Pull request merged**
